theme: jekyll-theme-architect
title: AOI-coaching & formation
description_short: Accueillez le changement, boostez vos projets !
description: >-
   Emmanuel BECKER<br />
   Formateur & coach professionnel certifié, titre RNCP<br /><br />
   Accompagnement au changement – coaching de vie - coaching professionnel – CoDéveloppement
   Expériences variées dans le secteur privé et dans le secteur public
   Vous êtes sujet au stress, soucieux de votre santé, vous souhaitez surmonter vos peurs, vous avez envie d’améliorer votre organisation, votre relationnel ou vous avez tout simplement besoin de prendre du temps pour vous et choisissez d’opter pour le développement personnel, a fortiori dans le contexte actuel de crise ? Passez à l’action !


